import {
  SECONDARY_BLUE,
  GRAYISH_BLUE,
  WHITE,
  GRAY_11_OPACITY_50,
  GRAY_7,
  GRAY_6,
  GRAY_6_95,
  GRAY_5,
  GRAY_4,
  GRAY_3,
  GRAY_1,
  BLACK,
  SHADOW_DARK,
  SHADOW_LIGHT,
  CHART_BLUE,
  GRAY_1_OPACITY,
  RAIN_1,
  RAIN_2,
  RAIN_3,
  RAIN_4,
  RAIN_5,
  RAIN_6,
  RAIN_7,
  RAIN_8,
  TRANSPARENT,
  GRAY_4_OPACITY_50,
  MEDIUM_BLUE,
  QUATERNARY_LIGHT,
  SECONDARY_LIGHT,
  PRIMARY_LIGHT,
  PRIMARY_DARK,
  QUATERNARY_DARK,
  SECONDARY_DARK,
  TERTIARY_DARK,
} from '@assets/colors';
import { Platform } from 'react-native';

const fonts = Platform.select({
  default: {
    regular: {
      fontFamily: 'Roboto-Regular',
      fontWeight: '400' as const,
    },
    medium: {
      fontFamily: 'Roboto-Medium',
      fontWeight: '500' as const,
    },
    bold: {
      fontFamily: 'Roboto-Bold',
      fontWeight: '600' as const,
    },
    heavy: {
      fontFamily: 'Roboto-Bold',
      fontWeight: '700' as const,
    },
  }
});

export const lightTheme = {
  dark: false,
  blue: false,
  colors: {
    primary: PRIMARY_LIGHT,
    background: QUATERNARY_LIGHT,
    card: WHITE,
    text: PRIMARY_LIGHT,
    notification: QUATERNARY_LIGHT,
    primaryText: BLACK,
    secondaryText: PRIMARY_LIGHT,
    border: SECONDARY_LIGHT,
    inputBackground: SECONDARY_LIGHT,
    inputButtonBackground: QUATERNARY_LIGHT,
    mapButtonBackground: QUATERNARY_LIGHT,
    relocateButtonBackground: SECONDARY_BLUE,
    mapButtonBorder: PRIMARY_LIGHT,
    headerBackground: QUATERNARY_LIGHT,
    timeStepBackground: SECONDARY_LIGHT,
    shadow: SHADOW_LIGHT,
    screenBackground: QUATERNARY_LIGHT,
    cardHeader: SECONDARY_LIGHT,
    cardShadow: PRIMARY_LIGHT,
    warningsIconFill: PRIMARY_LIGHT,
    selectedDayBackground: SECONDARY_LIGHT,
    chartPrimaryLine: PRIMARY_LIGHT,
    chartSecondaryLine: SECONDARY_BLUE,
    chartGrid: SECONDARY_LIGHT,
    chartGridDay: BLACK,
    hourListText: BLACK,
    secondaryBorder: SECONDARY_LIGHT,
    tabBarInactive: QUATERNARY_DARK,
    tabBarActive: PRIMARY_LIGHT,
    timeSliderObservationText: PRIMARY_LIGHT,
    timeSliderTick: PRIMARY_LIGHT,
    listTint: SECONDARY_LIGHT,
    rain: {
      0: TRANSPARENT,
      1: RAIN_1,
      2: RAIN_2,
      3: RAIN_3,
      4: RAIN_4,
      5: RAIN_5,
      6: RAIN_6,
      7: RAIN_7,
      8: RAIN_8,
    },
    accordionContentBackground: 'rgb(246,249,253)',
    modalBackground: WHITE,
    selectedButton: WHITE,
    warningCard: '#E8EFF5',
    warningCardBorder: MEDIUM_BLUE,
    weatherButtonBackground: GRAY_11_OPACITY_50,
    meteorologistSnapshotCard: '#f3f3f3',
  },
  fonts
};

export const darkTheme = {
  dark: true,
  blue: false,
  colors: {
    primary: PRIMARY_DARK,
    background: QUATERNARY_DARK,
    card: BLACK,
    text: PRIMARY_LIGHT,
    notification: QUATERNARY_DARK,
    primaryText: WHITE,
    secondaryText: PRIMARY_DARK,
    border: SECONDARY_DARK,
    inputBackground: QUATERNARY_DARK,
    inputButtonBackground: QUATERNARY_DARK,
    mapButtonBackground: QUATERNARY_DARK,
    relocateButtonBackground: QUATERNARY_DARK,
    mapButtonBorder: PRIMARY_DARK,
    headerBackground: QUATERNARY_DARK,
    timeStepBackground: SECONDARY_DARK,
    shadow: SHADOW_DARK,
    screenBackground: QUATERNARY_DARK,
    cardHeader: SECONDARY_DARK,
    cardShadow: PRIMARY_DARK,
    warningsIconFill: PRIMARY_DARK,
    selectedDayBackground: SECONDARY_DARK,
    chartPrimaryLine: PRIMARY_DARK,
    chartSecondaryLine: SECONDARY_DARK,
    chartGrid: SECONDARY_DARK,
    chartGridDay: WHITE,
    hourListText: WHITE,
    secondaryBorder: SECONDARY_LIGHT,
    tabBarInactive: WHITE,
    tabBarActive: PRIMARY_DARK,
    timeSliderObservationText: PRIMARY_DARK,
    timeSliderTick: PRIMARY_DARK,
    listTint: SECONDARY_DARK,
    rain: {
      0: TRANSPARENT,
      1: RAIN_1,
      2: RAIN_2,
      3: RAIN_3,
      4: RAIN_4,
      5: RAIN_5,
      6: RAIN_6,
      7: RAIN_7,
      8: RAIN_8,
    },
    accordionContentBackground: 'rgb(246,249,253)',
    modalBackground: 'rgb(25,25,25)',
    selectedButton: QUATERNARY_DARK,
    warningCard: GRAY_6,
    warningCardBorder: GRAY_4,
    weatherButtonBackground: GRAY_4_OPACITY_50,
    meteorologistSnapshotCard: GRAY_6,
  },
  fonts,
};

export const blueTheme = {
  dark: true,
  blue: true,
  colors: {
    primary: WHITE,
    background: '#0F0F2D',
    card: GRAY_7,
    text: WHITE,
    notification: WHITE,
    primaryText: WHITE,
    secondaryText: GRAY_1,
    border: '#BDD7E9',
    inputBackground: GRAY_4_OPACITY_50,
    inputButtonBackground: GRAY_5,
    mapButtonBackground: GRAY_6_95,
    relocateButtonBackground: GRAY_6,
    mapButtonBorder: GRAY_7,
    headerBackground: GRAY_6,
    timeStepBackground: GRAY_6,
    shadow: SHADOW_DARK,
    screenBackground: GRAY_7,
    cardHeader: 'rgba(21, 24, 58, 0.4)',
    cardShadow: BLACK,
    warningsIconFill: BLACK,
    selectedDayBackground: GRAY_4,
    chartPrimaryLine: CHART_BLUE,
    chartSecondaryLine: GRAYISH_BLUE,
    chartGrid: GRAY_3,
    chartGridDay: WHITE,
    hourListText: WHITE,
    secondaryBorder: TERTIARY_DARK,
    tabBarInactive: WHITE,
    tabBarActive: '#00D7FF',
    timeSliderObservationText: GRAY_1,
    timeSliderTick: GRAY_1,
    listTint: GRAY_1_OPACITY,
    rain: {
      0: TRANSPARENT,
      1: RAIN_1,
      2: RAIN_2,
      3: RAIN_3,
      4: RAIN_4,
      5: RAIN_5,
      6: RAIN_6,
      7: RAIN_7,
      8: RAIN_8,
    },
    accordionContentBackground: 'rgb(246,249,253)',
    modalBackground: '#1F2060',
    selectedButton: '#1F2060',
    warningCard: 'rgba(76, 76, 103, 0.6)',
    warningCardBorder: 'rgb(147, 184, 209)',
    weatherButtonBackground: GRAY_4_OPACITY_50,
    meteorologistSnapshotCard: 'rgba(76, 76, 103, 0.6)',
  },
  fonts,
};
