const termsEn = `
# Policy on the publication of data, draft products and official products on the website
IDEAM, in line with its objective of promoting a culture of transparency, adopts the principle of proactive disclosure of information. This principle encourages entities and institutions to publish and disseminate documents and records that reflect state activities and matters of public interest in a widespread, routine, updated, accessible, and understandable manner. The use of electronic media is highlighted as a fundamental tool to facilitate and enhance this disclosure of public information, ensuring that it is available to all citizens effectively and efficiently.

The publication scheme serves as the instrument to inform citizens about the availability of public information, detailing the management and dissemination of such information. This scheme is regulated by Law 1712 of 2014, known as the Transparency and Access to National Public Information Law, which establishes the relevant regulations to guarantee access to information for all citizens.

In this regard, transparency is not an end in itself, but a means through which public administration becomes more efficient, and citizens are informed in advance about the actions of public officials. This is achieved through the ethical conduct of public servants, continuous public accountability, and the guarantee of access to public information.

The information generated by public entities may be considered a public good. Consequently, the Political Constitution of Colombia establishes the right of citizens to access such information, to achieve more effective, transparent administrations focused on improving citizens' quality of life.

Article 20 of the Political Constitution of Colombia establishes the fundamental right of access to information; however, Article 15 also enshrines rights and guarantees for individuals who are the holders of such information, including protection of personal and family privacy, protection of one's good name, and the right to know, update, and rectify information that has been collected, stored, used, circulated, or deleted from databases and records of public and private entities.

Pursuant to Article 15 of the Political Constitution of Colombia, Statutory Law 1581 of October 17, 2012, was enacted, establishing the principles and provisions applicable to the processing of personal data recorded in any database of both public and private entities.

Accordingly, subsection (k) of Article 17 and subsection (f) of Article 18 of the afore mentioned law establish the duty of data controllers and processors to adopt an internal manual of policies and procedures to ensure proper compliance with the law, particularly for handling inquiries and complaints from data subjects.

In accordance with the current regulations on transparency and access to information, the website [www.ideam.gov.co](http://www.ideam.gov.co/) aims to make information related to the mission of the INSTITUTE OF HYDROLOGY, METEOROLOGY AND ENVIRONMENTAL STUDIES (IDEAM) available to the general public. Please read the following information carefully before using this website. The use of this digital publication and its content is subject to the conditions of use and confidentiality set forth below.

The following are the terms of a legal agreement for those who access this website. By accessing, browsing, or using this site, you acknowledge that you have read, understood, and agreed to comply with IDEAM's data protection policy, these terms, and all applicable regulations and laws.

## Principles
### Principle of Facilitation
Data controllers must facilitate the exercise of the right of access to information, excluding requirements that may obstruct or hinder it.

### Principle of Non-Discrimination
The data controller must provide information to all persons who request it, under equal conditions and without arbitrary distinctions.

### Principle of Free Access
Access to information is free of charge, and no fees may be charged beyond the cost of reproducing the information.

### Principle of Promptness
This principle seeks agility in administrative procedures and management.

## 1. Terms of Use
1.1 THE INSTITUTE OF HYDROLOGY, METEOROLOGY AND ENVIRONMENTAL STUDIES (IDEAM) may, without prior notice and at any time, revise these Terms of Use and any other information contained on this website by updating the Data Publication Policy.

1.2 IDEAM may also make improvements or changes to the services or programs described on this site at any time and without prior notice.

1.3 The user acknowledges that the submission of personal information is voluntary and made in response to specific requests by IDEAM in order to complete a procedure, file a complaint or claim, or access interactive mechanisms.

1.4 The materials on this website are protected by copyright. Any unauthorized use, as well as non-compliance with the terms, conditions, or notices contained herein, may violate applicable national regulations. Authorization to use this site shall automatically terminate if any of these conditions are breached, and the user must immediately destroy any material obtained or printed from this site, without prejudice to any legal action that IDEAM may initiate for such non-compliance.

1.5 The Terms and Conditions may be modified in whole or in part solely by IDEAM. Such changes shall take effect from the moment they are published or posted on the site, or from the moment they are notified to the user by any means, whichever occurs first.

1.6 To strengthen institutional measures within the framework of the right of access to public information, prior to the publication of official studies and technical documents, IDEAM may publish draft versions or progress updates of such studies and/or technical documents. Users are responsible for the proper use of this information, acknowledging that the source is a document and/or study still under development and not officially finalized by the entity. Therefore, IDEAM shall not be responsible for any harm resulting from misuse or failure to acknowledge the preliminary status of the information source.

1.7 IDEAM holds all rights to the website software, as well as industrial and intellectual property rights related to the content included therein, except for rights to products and services not owned by this entity, whose trademarks are registered to their respective owners and recognized as such by IDEAM.

1.8 In exercise of the fundamental right of access to information, any person may know of and access public information held or controlled by state entities. To guarantee this right, open data has been adopted as part of a national access policy aimed at building a more efficient, transparent, and participatory State through the use of ICTs and in compliance with national and international standards.

IDEAM has implemented an open data policy that facilitates free public access to technical data. This information may be consulted directly on the website under the Transparency -- Open Data section.

Open Data is understood as primary or unprocessed data available in standard, interoperable formats that facilitate access and reuse, under the custody of public or private entities performing public functions and made available freely and without restrictions so that third parties may reuse them and create derivative services.

The data and information published on this Open Data Portal are publicly accessible, allowing free use, exploitation, and/or transformation by third parties to create applications and content of their own. Permitted activities include redistribution, compilation, extraction, copying, dissemination, modification, and adaptation of the data.

Users who use, exploit, and/or transform the data and/or information from this website must cite the original source and indicate the date of the latest update when available. This ensures transparency and proper attribution in accordance with open data conditions.

1.9 It is prohibited to misrepresent the meaning of the data and/or information published on this portal. Metadata regarding update dates and applicable conditions of use and/or transformation must not be altered or removed.

1.10 The use of datasets shall be carried out by users at their own risk, and they shall be solely responsible to third parties for any damages arising from such use.

1.11 IDEAM shall not be responsible for the use made of its data by persons who transform and/or use such data, nor for any damages or economic losses, whether direct or indirect, resulting from the use and/or transformation of the data.

1.12 IDEAM has adopted the legally required security levels and implemented the necessary technical and organizational measures to prevent loss, misuse, alteration, unauthorized access, and theft of the data provided.

## 2. Modifications to the Terms of Use

2.1 IDEAM reserves the right to modify or correct the content of the terms and this website at any time and without prior notice to users.

2.2 The user agrees to periodically review this section to stay informed of such modifications. Each new access to the website shall be considered tacit acceptance of the new conditions.
`;

export default termsEn;